#!/bin/bash
#
# Script to prepare source code and binary distribution files of rEFInd.
# By Rod Smith, 3/11/2012
#
# Usage: ./mkdistrib version
# where "version" is a version number
# MUST be run from an x86-64 system, on which the current IA32 build
# (refind_ia32.efi) is already present in the same directory as this script


StartDir=`pwd`

make clean

# Prepare a place and copy files there....
mkdir -p ../snapshots/$1/refind-$1/icons
cp --preserve=timestamps icons/*icns ../snapshots/$1/refind-$1/icons/
cp -a docs images include libeg refind CREDITS.txt NEWS.txt BUILDING.txt COPYING.txt LICENSE.txt README.txt Make.common Makefile refind.conf-sample ../snapshots/$1/refind-$1

# Go there are prepare a souce code zip file....
cd ../snapshots/$1/
zip -9r refind-src-$1.zip refind-$1

# Build the source code into a binary
cd refind-$1
make
mkdir -p refind-bin-$1/refind
cp -a icons refind-bin-$1/refind/
cp --preserve=timestamps refind.conf-sample refind-bin-$1/refind/
cp refind/refind.efi refind-bin-$1/refind/refind_x64.efi
cp $StartDir/refind_ia32.efi refind-bin-$1/refind/
cp -a COPYING.txt LICENSE.txt README.txt docs CREDITS.txt refind-bin-$1
zip -9r ../refind-bin-$1.zip refind-bin-$1
cd ..
rm -r refind-$1
cd $StartDir
